name: Deploy Jira Plugin

on:
  workflow_dispatch:  # 👈 This enables manual trigger from GitHub UI

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    env:
      JIRA_URL: http://your-jira-server:8080
      PLUGIN_FILE: target/hello-jira-1.0.0.jar
      JIRA_USER: ${{ secrets.JIRA_USER }}
      JIRA_PASS: ${{ secrets.JIRA_PASS }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Java 8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'temurin'

      - name: Build plugin with Maven
        run: mvn clean package

      - name: Upload plugin to Jira
        run: |
          echo "Uploading plugin to $JIRA_URL"
          curl -u "$JIRA_USER:$JIRA_PASS" \
            -X POST \
            -H "Content-Type: multipart/form-data" \
            -F "plugin=@$PLUGIN_FILE" \
            "$JIRA_URL/rest/plugins/1.0/"
